# Generated by Django 5.0.3 on 2024-11-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='titulo',
            new_name='title',
        ),
    ]
